version: "3.7"

services:
  mongoshake:
    image: mongoshake:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./collector.conf:/mongo-shake/collector.conf:ro
    networks:
      - mongonet

networks:
  mongonet:
    external: true
    name: mongonet
    driver: bridge
